@server=http://localhost:4004
@username=alice
@password=


### Leaves
# @name Leaves_GET
GET {{server}}/odata/v4/school/Leaves
Authorization: Basic {{username}}:{{password}}


### Leaves
# @name Leaves_POST
POST {{server}}/odata/v4/school/Leaves
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  
  "studentName": "Samruddhi Chaure",
  "studentEmail": "samruddhi.chaure@cloudstine.com",
  "department": "cse",
  "leaveType": "Medical Leave",
  "fromDate": "2026-06-09",
  "toDate": "2026-06-10",
  "reason": "asdfghj",
  "status": "Rejected",
  "appliedOn": "2026-06-03T00:00:00.000Z",
  "comment": "NA"
}


### Leaves
# @name Leaves_PATCH
PATCH {{server}}/odata/v4/school/Leaves/11878079-9142-40c3-bfe7-38e95fb1bebb
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "11878079-9142-40c3-bfe7-38e95fb1bebb",
  "studentName": "studentName-11878079",
  "studentEmail": "studentEmail-11878079",
  "department": "department-11878079",
  "leaveType": "leaveType-11878079",
  "fromDate": "2020-12-08",
  "toDate": "2020-07-14",
  "reason": "reason-11878079",
  "status": "status-11878079",
  "appliedOn": "2012-02-07T00:00:00.000Z",
  "comment": "comment-11878079"
}


### Leaves
# @name Leaves_DELETE
DELETE {{server}}/odata/v4/school/Leaves/11878079-9142-40c3-bfe7-38e95fb1bebb
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Bonafide
# @name Bonafide_GET
GET {{server}}/odata/v4/school/Bonafide
Authorization: Basic {{username}}:{{password}}


### Bonafide
# @name Bonafide_POST
POST {{server}}/odata/v4/school/Bonafide
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "9950773b-af1f-4ba3-bf3d-b8a4d8572cfe",
  "studentName": "Samruddhi Chaure",
  "studentEmail": "samruddhi.chaure@cloudstine.com",
  "department": "cse",
  "purpose": "I require a Bonafide Certificate for processing my education loan application.",
  "noOfCopies": 2,
  "remark": "remark-9950773",
  "status": "Pending",
  "comment": "Required for education loan processing",
  "createdAt": "2005-07-28T00:00:00.000Z",
  "createdBy": "createdBy.5xa2d@example.com",
  "modifiedAt": "2006-08-05T00:00:00.000Z",
  "modifiedBy": "modifiedBy.5xa2d@example.org"
}


### Bonafide
# @name Bonafide_PATCH
PATCH {{server}}/odata/v4/school/Bonafide/9950773b-af1f-4ba3-bf3d-b8a4d8572cfe
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "9950773b-af1f-4ba3-bf3d-b8a4d8572cfe",
  "studentName": "studentName-9950773",
  "studentEmail": "studentEmail-9950773",
  "department": "department-9950773",
  "purpose": "purpose-9950773",
  "noOfCopies": 58,
  "remark": "remark-9950773",
  "status": "status-9950773",
  "comment": "comment-9950773",
  "createdAt": "2005-07-28T00:00:00.000Z",
  "createdBy": "createdBy.5xa2d@example.com",
  "modifiedAt": "2006-08-05T00:00:00.000Z",
  "modifiedBy": "modifiedBy.5xa2d@example.org"
}


### Bonafide
# @name Bonafide_DELETE
DELETE {{server}}/odata/v4/school/Bonafide/9950773b-af1f-4ba3-bf3d-b8a4d8572cfe
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Users
# @name Users_GET
GET {{server}}/odata/v4/school/Users
Authorization: Basic {{username}}:{{password}}


### Users
# @name Users_POST
POST {{server}}/odata/v4/school/Users
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "email": "samruddhi.chaure@cloudstine.com",
  "name": "Samruddhi Chaure",
  "mobileNumber": "9561124085",
  "dateOfBirth": "2001-10-05",
  "address": "Kharadi",
  "department": "cse",
  "guardianName": "Tanmay",
  "guardianNumber": "9876543210"
}


### Users
# @name Users_PATCH
PATCH {{server}}/odata/v4/school/Users/Users-11383793
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "email": "Users-11383793",
  "name": "name-11383793",
  "mobileNumber": "obileNumber-11383793",
  "dateOfBirth": "2007-11-14",
  "address": "address-11383793",
  "department": "department-11383793",
  "guardianName": "guardianName-11383793",
  "guardianNumber": "rdianNumber-11383793"
}


### Users
# @name Users_DELETE
DELETE {{server}}/odata/v4/school/Users/Users-11383793
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
