@server=http://localhost:4004
@username=alice
@password=


### Leaves
# @name Leaves_GET
GET {{server}}/odata/v4/school/Leaves
Authorization: Basic {{username}}:{{password}}


### Leaves
# @name Leaves_POST
POST {{server}}/odata/v4/school/Leaves
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "13593969-d4b9-407a-9daa-2eda1e2e2840",
  "studentName": "Samruddhi Chaure",
  "studentEmail": "samruddhi.chaure@cloudstine.com",
  "department": "Computer Science",
  "leaveType": "Medical Leave",
  "fromDate": "2026-06-11",
  "toDate": "2026-06-12",
  "reason": "Personal health issues",
  "status": "Pending",
  "appliedOn": "2026-06-10T00:00:00.000Z",
  "comment": "comment-13593969"
}


### Leaves
# @name Leaves_PATCH
PATCH {{server}}/odata/v4/school/Leaves/13593969-d4b9-407a-9daa-2eda1e2e2840
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "13593969-d4b9-407a-9daa-2eda1e2e2840",
  "studentName": "studentName-13593969",
  "studentEmail": "studentEmail-13593969",
  "department": "department-13593969",
  "leaveType": "leaveType-13593969",
  "fromDate": "2009-08-26",
  "toDate": "2013-11-12",
  "reason": "reason-13593969",
  "status": "status-13593969",
  "appliedOn": "2023-07-05T00:00:00.000Z",
  "comment": "comment-13593969"
}


### Leaves
# @name Leaves_DELETE
DELETE {{server}}/odata/v4/school/Leaves/13593969-d4b9-407a-9daa-2eda1e2e2840
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Bonafide
# @name Bonafide_GET
GET {{server}}/odata/v4/school/Bonafide
Authorization: Basic {{username}}:{{password}}


### Bonafide
# @name Bonafide_POST
POST {{server}}/odata/v4/school/Bonafide
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "5338929e-ab7d-4af6-8f31-6027c8f4b34c",
  "studentName": "Samruddhi Chaure",
  "studentEmail": "samruddhi.chaure@cloudstine.com",
  "department": "Computer Science",
  "purpose": "Education loan",
  "noOfCopies": 1,
  "remark": "wertyuio",
  "status": "Approved",
  "comment": "comment-5338929",
  "createdAt": "2026-06-11T00:00:00.000Z",
  "createdBy": "createdBy.36fjl@example.org",
  "modifiedAt": "2004-12-24T00:00:00.000Z",
  "modifiedBy": "modifiedBy.36fjl@example.org"
}


### Bonafide
# @name Bonafide_PATCH
PATCH {{server}}/odata/v4/school/Bonafide/5338929e-ab7d-4af6-8f31-6027c8f4b34c
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "5338929e-ab7d-4af6-8f31-6027c8f4b34c",
  "studentName": "studentName-5338929",
  "studentEmail": "studentEmail-5338929",
  "department": "department-5338929",
  "purpose": "purpose-5338929",
  "noOfCopies": 38,
  "remark": "remark-5338929",
  "status": "status-5338929",
  "comment": "comment-5338929",
  "createdAt": "2014-05-19T00:00:00.000Z",
  "createdBy": "createdBy.36fjl@example.org",
  "modifiedAt": "2004-12-24T00:00:00.000Z",
  "modifiedBy": "modifiedBy.36fjl@example.org"
}


### Bonafide
# @name Bonafide_DELETE
DELETE {{server}}/odata/v4/school/Bonafide/5338929e-ab7d-4af6-8f31-6027c8f4b34c
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Users
# @name Users_GET
GET {{server}}/odata/v4/school/Users
Authorization: Basic {{username}}:{{password}}


### Users
# @name Users_POST
POST {{server}}/odata/v4/school/Users
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
      "address": "Kharadi",
      "dateOfBirth": "2001-02-01",
      "department": "Cse",
      "email": "samruddhi.chaure@cloudstine.com",
      "guardianName": "Tanmay",
      "guardianNumber": "9312345678",
      "mobileNumber": "9012345678",
      "name": "Samruddhi Chaure"
}


### Users
# @name Users_PATCH
PATCH {{server}}/odata/v4/school/Users/Users-27881260
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "email": "Users-27881260",
  "name": "name-27881260",
  "mobileNumber": "obileNumber-27881260",
  "dateOfBirth": "2015-08-15",
  "address": "address-27881260",
  "department": "department-27881260",
  "guardianName": "guardianName-27881260",
  "guardianNumber": "rdianNumber-27881260"
}


### Users
# @name Users_DELETE
DELETE {{server}}/odata/v4/school/Users/Users-27881260
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
