@server=http://localhost:4004
@username=alice
@password=


### Leaves
# @name Leaves_GET
GET {{server}}/school/Leaves
Authorization: Basic {{username}}:{{password}}


### Leaves
# @name Leaves_POST
POST {{server}}/school/Leaves
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "23221483-dded-4d80-b984-a4d2cd372c57",
  "studentName": "studentName-23221483",
  "studentEmail": "studentEmail-23221483",
  "department": "department-23221483",
  "leaveType": "leaveType-23221483",
  "fromDate": "2006-11-06",
  "toDate": "2000-11-09",
  "reason": "reason-23221483",
  "status": "status-23221483",
  "appliedOn": "2017-03-02T00:00:00.000Z",
  "comment": "comment-23221483"
}


### Leaves
# @name Leaves_PATCH
PATCH {{server}}/school/Leaves/23221483-dded-4d80-b984-a4d2cd372c57
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "23221483-dded-4d80-b984-a4d2cd372c57",
  "studentName": "studentName-23221483",
  "studentEmail": "studentEmail-23221483",
  "department": "department-23221483",
  "leaveType": "leaveType-23221483",
  "fromDate": "2006-11-06",
  "toDate": "2000-11-09",
  "reason": "reason-23221483",
  "status": "status-23221483",
  "appliedOn": "2017-03-02T00:00:00.000Z",
  "comment": "comment-23221483"
}


### Leaves
# @name Leaves_DELETE
DELETE {{server}}/school/Leaves/23221483-dded-4d80-b984-a4d2cd372c57
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Bonafide
# @name Bonafide_GET
GET {{server}}/school/Bonafide
Authorization: Basic {{username}}:{{password}}


### Bonafide
# @name Bonafide_POST
POST {{server}}/school/Bonafide
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "36487923-4060-4e13-98d4-2dc54dc376ff",
  "studentName": "Samruddhi Chaure",
  "studentEmail": "samruddhi.chaure@cloudstine.com",
  "department": "Computer Science",
  "purpose": "Education Loan",
  "noOfCopies": 1,
  "remark": "dfghjkgv",
  "status": "Pending",
  "comment": "comment-3648792",
  "createdAt": "2026-06-10T00:00:00.000Z",
  "createdBy": "createdBy.267fc@example.com",
  "modifiedAt": "2026-06-06T00:00:00.000Z",
  "modifiedBy": "modifiedBy.267fc@example.org"
}


### Bonafide
# @name Bonafide_PATCH
PATCH {{server}}/school/Bonafide/36487923-4060-4e13-98d4-2dc54dc776ff
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "36487923-4060-4e13-98d4-2dc54dc776ff",
  "studentName": "studentName-3648792",
  "studentEmail": "studentEmail-3648792",
  "department": "department-3648792",
  "purpose": "purpose-3648792",
  "noOfCopies": 12,
  "remark": "remark-3648792",
  "status": "status-3648792",
  "comment": "comment-3648792",
  "createdAt": "2004-07-10T00:00:00.000Z",
  "createdBy": "createdBy.267fc@example.com",
  "modifiedAt": "2018-02-06T00:00:00.000Z",
  "modifiedBy": "modifiedBy.267fc@example.org"
}


### Bonafide
# @name Bonafide_DELETE
DELETE {{server}}/school/Bonafide/36487923-4060-4e13-98d4-2dc54dc776ff
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Users
# @name Users_GET
GET {{server}}/school/Users
Authorization: Basic {{username}}:{{password}}


### Users
# @name Users_POST
POST {{server}}/school/Users
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "email": "samruddhichaure9000@gmail.com",
  "name": "Samruddhi Chaure",
  "firstName": "Samruddhi",
  "lastName": "Chaure",
  "mobileNumber": "496588310",
  "dateOfBirth": "2002-03-07",
  "address": "kharadi Pune",
  "department": "Computer Science",
  "guardianName": "Aman",
  "guardianNumber": "2134567890",
  "role": "Admin"
}


### Users
# @name Users_PATCH
PATCH {{server}}/school/Users/Users-694306
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "email": "Users-694306",
  "name": "name-694306",
  "firstName": "firstName-694306",
  "lastName": "lastName-694306",
  "mobileNumber": "mobileNumber-694306",
  "dateOfBirth": "2004-07-14",
  "address": "address-694306",
  "department": "department-694306",
  "guardianName": "guardianName-694306",
  "guardianNumber": "uardianNumber-694306",
  "role": "role-694306"
}


### Users
# @name Users_DELETE
DELETE {{server}}/school/Users/Users-694306
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### UserInfo
# @name UserInfo_GET
GET {{server}}/school/UserInfo
Authorization: Basic {{username}}:{{password}}


### UserInfo
# @name UserInfo_POST
POST {{server}}/school/UserInfo
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "id": "UserInfo-12192372",
  "name": "name-12192372",
  "email": "email-12192372",
  "role": "role-12192372",
  "token": "token-12192372"
}


### UserInfo
# @name UserInfo_PATCH
PATCH {{server}}/school/UserInfo/UserInfo-12192372
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "id": "UserInfo-12192372",
  "name": "name-12192372",
  "email": "email-12192372",
  "role": "role-12192372",
  "token": "token-12192372"
}


### UserInfo
# @name UserInfo_DELETE
DELETE {{server}}/school/UserInfo/UserInfo-12192372
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
